project_id = "gtakgctmtayalcbpnryg"

[functions.clever-service]
verify_jwt = false

[functions.compress-storage-images]
verify_jwt = false

[functions.procurement-webhook]
verify_jwt = false

[functions.procurement-quote-webhook]
verify_jwt = false
